[package]
name = "aoc-2019"
version = "0.1.0"
authors = ["Rasmus Rosengren <rasmus.rosengren@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
permutohedron = "0.2.4"