on: [push, pull_request]

name: "[2020 rust] Build, test, and format"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        working-directory: 2020/rust
        run: rustup default nightly

      - name: Run cargo check
        working-directory: 2020/rust
        run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        working-directory: 2020/rust
        run: rustup default nightly

      - name: Run cargo test
        working-directory: 2020/rust
        run: cargo test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        working-directory: 2020/rust
        run: rustup default nightly

      - name: Run cargo fmt
        working-directory: 2020/rust
        run: cargo fmt --all -- --format
        uses: actions-rs/cargo@v1

      - name: Run cargo clippy
        working-directory: 2020/rust
        run: cargo clippy -- -D warning
